{{- if and .Values.configMap.enabled (not .Values.configMap.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consensus-proxy.fullname" . }}
  namespace: {{ include "consensus-proxy.namespace" . }}
  labels:
    {{- include "consensus-proxy.labels" . | nindent 4 }}
    {{- with .Values.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.toml: |
    {{- .Values.configMap.config | nindent 4 }}
{{- end }}
