{{- if .Values.horizontalPodAutoscaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "consensus-proxy.fullname" . }}
  namespace: {{ include "consensus-proxy.namespace" . }}
  labels:
    {{- include "consensus-proxy.labels" . | nindent 4 }}
    {{- with .Values.horizontalPodAutoscaler.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.horizontalPodAutoscaler.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "consensus-proxy.fullname" . }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.horizontalPodAutoscaler.maxReplicas }}
  metrics:
    {{- if .Values.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .Values.horizontalPodAutoscaler.customMetrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.horizontalPodAutoscaler.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
