name: 'Release'

on:
  push:
    branches:
      - main

# Use Go semantic release action to create a release when a new tag is pushed

jobs:
  release-go:
    name: 'Release Go Application'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Go
        uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3
        with:
          go-version: '1.25'

      - name: Create Release
        uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: 'CHANGELOG.md'